#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Unity Skills Python Helper
# Auto-generated by UnitySkills

# CRITICAL: Fix Windows console encoding BEFORE any other imports or print statements
# This must be at the very top of the module to work correctly
import sys
if sys.platform == 'win32':
    import codecs
    if hasattr(sys.stdout, 'buffer'):
        sys.stdout = codecs.getwriter('utf-8')(sys.stdout.buffer, 'replace')
    if hasattr(sys.stderr, 'buffer'):
        sys.stderr = codecs.getwriter('utf-8')(sys.stderr.buffer, 'replace')

import requests
import time
import json
import os
import re
import threading
from typing import Any, Dict, List, Optional
from urllib.parse import urlencode

__version__ = "1.8.0"

UNITY_URL = "http://localhost:8090"
DEFAULT_PORT = 8090
PORT_RANGE_START = 8090
PORT_RANGE_END = 8100

# Timeout constants (seconds)
DEFAULT_CALL_TIMEOUT = 900
HEALTH_TIMEOUT = 2
SCAN_TIMEOUT = 1

def get_registry_path():
    return os.path.join(os.path.expanduser("~"), ".unity_skills", "registry.json")


def _load_registry():
    reg_path = get_registry_path()
    if not os.path.exists(reg_path):
        return {}
    try:
        with open(reg_path, 'r', encoding='utf-8') as f:
            return json.load(f)
    except IOError:
        return {}
    except json.JSONDecodeError as exc:
        print(f"[unity-skills] registry.json is invalid JSON: {exc}", file=sys.stderr)
        return {}


def _get_agent_id():
    try:
        config_path = os.path.join(os.path.dirname(__file__), 'agent_config.json')
        if os.path.exists(config_path):
            with open(config_path, 'r', encoding='utf-8') as f:
                return json.load(f).get('agentId', 'Python')
    except (IOError, json.JSONDecodeError):
        pass
    return 'Python'


def _version_matches(actual_version: str, target: str) -> bool:
    """
    Version prefix matching with Unity 6 special format support.

    Unity 6 uses internal version like '6000.0.xxf1', so user input '6' or 'Unity 6'
    should match '6000.x.x'. Traditional versions like '2022.3.12f1' use direct prefix matching.

    Examples:
        _version_matches("6000.0.28f1", "6")       -> True
        _version_matches("6000.0.28f1", "Unity 6")  -> True
        _version_matches("6000.0.28f1", "6000")     -> True
        _version_matches("2022.3.12f1", "2022")     -> True
        _version_matches("2022.3.12f1", "2022.3")   -> True
        _version_matches("2022.3.12f1", "6")        -> False
    """
    if not actual_version or not target:
        return False

    # Strip "Unity" prefix and whitespace from target
    cleaned = target.strip()
    if cleaned.lower().startswith("unity"):
        cleaned = cleaned[5:].strip()

    if not cleaned:
        return False

    # Unity 6 special mapping: user says "6", "6.1", "6.2" etc -> match "6000."
    if cleaned.split(".")[0] == "6" and not cleaned.startswith("6000"):
        return actual_version.startswith("6000.")

    # Direct prefix match for everything else (e.g. "6000", "2022", "2022.3")
    return actual_version.startswith(cleaned)


def _is_retryable_transport_error(result: Dict[str, Any]) -> bool:
    if not isinstance(result, dict) or result.get('success'):
        return False

    transport_error = result.get('transportError')
    if transport_error in {'connection', 'timeout'}:
        return True

    error_text = str(result.get('error', '')).lower()
    return (
        'cannot connect' in error_text
        or 'timed out' in error_text
        or 'read timed out' in error_text
        or 'connection aborted' in error_text
    )


class UnitySkills:
    """
    Client for interacting with a specific Unity Editor instance.
    """
    def __init__(self, port: int = None, target: str = None, url: str = None, version: str = None, agent_id: str = None, timeout: int = None):
        """
        Initialize client.
        Args:
            port: Connect to specific localhost port (e.g. 8091)
            target: Connect to instance by Name or ID (e.g. "MyGame" or "MyGame_A1B2") - auto-discovers port.
            url: Full URL override.
            version: Connect to instance by Unity version (e.g. "6", "2022", "2022.3") - auto-discovers port.
            agent_id: Custom agent identifier (e.g. "MyScript", "ClaudeCode")
            timeout: Request timeout in seconds (default: 900)
        Priority: url > port > target > version > default port 8090
        """
        self.url = url
        self.agent_id = agent_id or _get_agent_id()
        self.timeout = timeout or DEFAULT_CALL_TIMEOUT
        # Reuse a Session so TCP connections stay warm across requests.
        self._session = requests.Session()
        self._session.headers.update({
            'X-Agent-Id': self.agent_id,
            'User-Agent': f'unity-skills-python/{__version__}',
        })

        if not self.url:
            if port:
                self.url = f"http://localhost:{port}"
            elif target:
                found_port = self._find_port_by_target(target)
                if found_port:
                    self.url = f"http://localhost:{found_port}"
                else:
                    raise ValueError(f"Could not find Unity instance matching '{target}' in registry.")
            elif version:
                found_port = self._find_port_by_version(version)
                if found_port:
                    self.url = f"http://localhost:{found_port}"
                else:
                    raise ValueError(f"Could not find Unity instance matching version '{version}'.")
            else:
                # Auto-discover: scan 8090-8100 for first responding instance
                found_port = self._find_first_available()
                self.url = f"http://localhost:{found_port}"

        # Sync timeout from Unity server if user didn't specify one
        if not timeout:
            self._sync_timeout_from_server()

    def _sync_timeout_from_server(self):
        """Fetch requestTimeoutMinutes from /health and apply as self.timeout."""
        try:
            resp = self._session.get(f"{self.url}/health", timeout=HEALTH_TIMEOUT)
            if resp.status_code == 200:
                minutes = resp.json().get('requestTimeoutMinutes')
                if minutes and isinstance(minutes, (int, float)) and minutes > 0:
                    self.timeout = int(minutes) * 60
        except Exception:
            pass

    def _find_first_available(self) -> int:
        """Scan ports 8090-8100 and return the first responsive Unity instance."""
        for port in range(PORT_RANGE_START, PORT_RANGE_END + 1):
            try:
                resp = requests.get(f"http://localhost:{port}/health", timeout=SCAN_TIMEOUT)
                if resp.status_code == 200:
                    return port
            except (requests.exceptions.RequestException, ValueError):
                continue
        raise ConnectionError(f"No Unity instance found on ports {PORT_RANGE_START}-{PORT_RANGE_END}. Is UnitySkills server running?")

    def _find_port_by_target(self, target: str) -> Optional[int]:
        data = _load_registry()
        for path, info in data.items():
            if info.get('id') == target:
                return info.get('port')
        for path, info in data.items():
            if info.get('name') == target:
                return info.get('port')
        return None

    def _find_port_by_version(self, version: str) -> Optional[int]:
        """
        Find a Unity instance port by version string.

        Three-stage search strategy (decreasing efficiency):
        1. Check registry - read unityVersion field from registry.json (no HTTP overhead)
        2. Probe health - when registry has no version info (old server), call /health on registered ports
        3. Scan ports - when registry is empty/missing, scan ports 8090-8100
        """
        registry_data = _load_registry() or None

        # Stage 1: Check registry unityVersion field
        if registry_data:
            for path, info in registry_data.items():
                reg_version = info.get('unityVersion')
                if reg_version and _version_matches(reg_version, version):
                    port = info.get('port')
                    if port:
                        return port

            # Stage 2: Probe /health for registered ports without version info
            ports_without_version = []
            for path, info in registry_data.items():
                if not info.get('unityVersion') and info.get('port'):
                    ports_without_version.append(info['port'])

            for port in ports_without_version:
                try:
                    resp = requests.get(f"http://localhost:{port}/health", timeout=HEALTH_TIMEOUT)
                    if resp.status_code == 200:
                        health_data = resp.json()
                        health_version = health_data.get('unityVersion')
                        if health_version and _version_matches(health_version, version):
                            return port
                except (requests.exceptions.RequestException, ValueError):
                    continue

        # Stage 3: Scan port range (fallback when registry is empty/missing)
        if not registry_data:
            for port in range(PORT_RANGE_START, PORT_RANGE_END + 1):
                try:
                    resp = requests.get(f"http://localhost:{port}/health", timeout=SCAN_TIMEOUT)
                    if resp.status_code == 200:
                        health_data = resp.json()
                        health_version = health_data.get('unityVersion')
                        if health_version and _version_matches(health_version, version):
                            return port
                except (requests.exceptions.RequestException, ValueError):
                    continue

        return None

    def _post_skill(self, skill_name: str, payload: Dict[str, Any], mode: str = None, timeout: Optional[int] = None):
        params = {}
        if mode:
            params['mode'] = mode
        qs = f"?{urlencode(params)}" if params else ""
        json_data = json.dumps(payload, ensure_ascii=False)
        response = self._session.post(
            f"{self.url}/skill/{skill_name}{qs}",
            data=json_data.encode('utf-8'),
            headers={'Content-Type': 'application/json; charset=utf-8'},
            timeout=timeout or self.timeout
        )
        response.encoding = 'utf-8'
        return response

    def call(self, skill_name: str, verbose: bool = False, wait_for_job: bool = False,
             job_timeout: float = 60.0, _retries: int = 3, _retry_delay: float = 2.0, **kwargs) -> Dict[str, Any]:
        """
        Call a skill on this instance with automatic retry on connection errors.

        Args:
            skill_name: Name of the skill to call
            verbose: Whether to return verbose output
            _retries: Number of retries on connection error (default 3)
            _retry_delay: Base delay between retries in seconds (default 2.0), uses progressive backoff

        Returns a normalized response with 'success' field and flattened result data.
        """
        last_error = None
        for attempt in range(_retries + 1):
            try:
                kwargs['verbose'] = verbose
                response = self._post_skill(skill_name, kwargs)

                try:
                    data = response.json()
                except ValueError:
                    return {'success': False, 'error': f"Invalid JSON response: {response.text}"}

                if data.get('status') == 'success':
                    result = data.get('result', {})
                    normalized = {'success': True}
                    if isinstance(result, dict):
                        normalized.update(result)
                    else:
                        normalized['result'] = result
                    if wait_for_job and isinstance(normalized, dict) and normalized.get('jobId'):
                        return self.wait_for_job(normalized['jobId'], timeout=job_timeout)
                    return normalized
                elif data.get('status') == 'error':
                    return {
                        'success': False,
                        'error': data.get('error', 'Unknown error'),
                        'message': data.get('message', '')
                    }
                else:
                    if wait_for_job and isinstance(data, dict) and data.get('jobId'):
                        return self.wait_for_job(data['jobId'], timeout=job_timeout)
                    return data

            except requests.exceptions.Timeout as e:
                last_error = e
                if attempt < _retries:
                    time.sleep(_retry_delay * (attempt + 1))
                    continue
                return {
                    'success': False,
                    'error': f"Request to {self.url} timed out after {self.timeout} seconds.",
                    'transportError': 'timeout',
                    'retryable': True,
                    'suggestion': 'Unity may still be compiling scripts or processing a long-running operation. Wait a moment and retry.',
                }
            except requests.exceptions.ConnectionError as e:
                last_error = e
                if attempt < _retries:
                    time.sleep(_retry_delay * (attempt + 1))
                    continue
                return {
                    'success': False,
                    'error': f"Cannot connect to {self.url}. Unity instance may be down.",
                    'transportError': 'connection',
                    'retryable': True,
                    'suggestion': 'Unity may be recompiling scripts (Domain Reload). Wait 3-5 seconds and retry.',
                    'hint': 'Check if server is running: Window > UnitySkills > Start Server'
                }
            except Exception as e:
                return {'success': False, 'error': str(e)}

    def dry_run_skill(self, skill_name: str, **kwargs) -> Dict[str, Any]:
        try:
            response = self._post_skill(skill_name, kwargs, mode='dryRun')
            return response.json()
        except ValueError as exc:
            return {'status': 'error', 'error': f'Invalid JSON response: {exc}'}
        except Exception as exc:
            return {'status': 'error', 'error': str(exc)}

    def plan_skill(self, skill_name: str, **kwargs) -> Dict[str, Any]:
        try:
            response = self._post_skill(skill_name, kwargs, mode='plan')
            return response.json()
        except ValueError as exc:
            return {'status': 'error', 'error': f'Invalid JSON response: {exc}'}
        except Exception as exc:
            return {'status': 'error', 'error': str(exc)}

    def plan_workflow(self, skills: List[Dict[str, Any]]) -> Dict[str, Any]:
        return self.call('workflow_plan', skillsJson=json.dumps(skills, ensure_ascii=False))

    def get_job_status(self, job_id: str) -> Dict[str, Any]:
        return self.call('job_status', jobId=job_id)

    def get_job_logs(self, job_id: str, limit: int = 100) -> Dict[str, Any]:
        return self.call('job_logs', jobId=job_id, limit=limit)

    def wait_for_job(self, job_id: str, timeout: float = 60.0) -> Dict[str, Any]:
        timeout_ms = max(1000, int(timeout * 1000))
        result = self.call('job_wait', jobId=job_id, timeoutMs=timeout_ms)
        if isinstance(result, dict) and result.get('reportId'):
            report = self.call('batch_report_get', reportId=result['reportId'])
            if isinstance(report, dict) and report.get('success'):
                result['report'] = report
        return result


# Global Default Client (lazy initialization)
_default_client = None

def _get_default_client():
    """Lazily initialize the default client and auto-discover an instance on first use."""
    global _default_client
    if _default_client is None:
        _default_client = UnitySkills()
    return _default_client

_auto_workflow_enabled = True  # Backward-compatible flag; single-call workflow is now handled by the Unity server.
_current_workflow_active = False  # Is an explicit WorkflowContext currently active?
_workflow_lock = threading.Lock()  # Protects _auto_workflow_enabled and _current_workflow_active

def set_auto_workflow(enabled: bool):
    """Backward-compatible toggle. Single-call auto-workflow is owned by the Unity server."""
    global _auto_workflow_enabled
    with _workflow_lock:
        _auto_workflow_enabled = enabled

def is_auto_workflow_enabled() -> bool:
    """Check if auto-workflow is enabled."""
    with _workflow_lock:
        return _auto_workflow_enabled

def connect(port: int = None, target: str = None, version: str = None) -> UnitySkills:
    """
    Create a new UnitySkills client.
    Args:
        port: Connect to specific localhost port (e.g. 8091)
        target: Connect to instance by Name or ID
        version: Connect to instance by Unity version (e.g. "6", "2022", "2022.3")
    """
    return UnitySkills(port=port, target=target, version=version)

def set_unity_version(version: str):
    """
    Set target Unity version and reconfigure the default client.

    This is the primary way for AI agents to route to a specific Unity version
    when multiple instances are running.

    Args:
        version: Unity version string, e.g. "6", "Unity 6", "2022", "2022.3"

    Example:
        import unity_skills
        unity_skills.set_unity_version("6")       # Switch to Unity 6
        unity_skills.call_skill("gameobject_create", name="Cube")  # Auto-routes
    """
    global _default_client
    _default_client = UnitySkills(version=version)

def list_instances() -> list:
    """Return list of active Unity instances from registry."""
    data = _load_registry()
    results = []
    for info in data.values():
        results.append(dict(info))
    return results

def dry_run_skill(skill_name: str, **kwargs) -> Dict[str, Any]:
    """Validate a Unity skill call without executing it."""
    return _get_default_client().dry_run_skill(skill_name, **kwargs)


def plan_skill(skill_name: str, **kwargs) -> Dict[str, Any]:
    """Preview a Unity skill call with generic/semantic planning details."""
    return _get_default_client().plan_skill(skill_name, **kwargs)


def plan_workflow(goal: str = None, target_output: str = None, max_depth: int = 3,
                  skills: Optional[List[Dict[str, Any]]] = None) -> Dict[str, Any]:
    """
    Plan a multi-step workflow.

    Preferred usage:
        plan_workflow(skills=[{"name": "gameobject_create", "params": {...}}, ...])

    Backward-compatible fallback:
        plan_workflow(goal="build player", target_output="scene")
    """
    if skills is None and isinstance(goal, list):
        skills = goal
        goal = None

    if skills is not None:
        return _get_default_client().plan_workflow(skills)

    result: Dict[str, Any] = {'status': 'plan', 'goal': goal, 'targetOutput': target_output}
    if goal:
        result['recommendations'] = find_skills(goal)
    if target_output:
        result['dependencyChain'] = get_skill_chain(target_output, max_depth=max_depth)
    result['note'] = 'Pass skills=[...] to call the server-side workflow_plan aggregator.'
    return result


def call_skill(skill_name: str, **kwargs) -> Dict[str, Any]:
    """Call a Unity skill. Single-call auto-workflow is handled by the Unity server."""
    return _get_default_client().call(skill_name, **kwargs)


def get_job_status(job_id: str) -> Dict[str, Any]:
    """Get status for an asynchronous UnitySkills job."""
    return _get_default_client().get_job_status(job_id)


def get_job_logs(job_id: str, limit: int = 100) -> Dict[str, Any]:
    """Get structured logs for an asynchronous UnitySkills job."""
    return _get_default_client().get_job_logs(job_id, limit=limit)


def wait_for_job(job_id: str, timeout: float = 60.0) -> Dict[str, Any]:
    """Wait for a UnitySkills job and include the final batch report when available."""
    return _get_default_client().wait_for_job(job_id, timeout=timeout)


class WorkflowContext:
    """
    Workflow context manager for batching multiple operations into a single workflow task.

    Usage:
        with WorkflowContext('Create Scene', 'Build player and environment'):
            call_skill('gameobject_create', name='Player')
            call_skill('component_add', name='Player', componentType='Rigidbody')
    """
    def __init__(self, tag: str, description: str = ''):
        self.tag = tag
        self.description = description
        self._started = False
        self._task_id = None

    def _matches_status(self, status: Dict[str, Any]) -> bool:
        if not status.get('success') or not status.get('isRecording'):
            return False

        current_tag = status.get('currentTaskTag')
        current_description = status.get('currentTaskDescription') or ''
        if current_tag != self.tag:
            return False

        return current_description == (self.description or '')

    def _recover_started_task(self, failed_result: Dict[str, Any]) -> bool:
        global _current_workflow_active

        if not _is_retryable_transport_error(failed_result):
            return False
        if not wait_for_unity(timeout=10.0):
            return False

        status = _get_default_client().call('workflow_session_status')
        if not self._matches_status(status):
            return False

        self._started = True
        self._task_id = status.get('currentTaskId')
        with _workflow_lock:
            _current_workflow_active = True
        return True

    def _recover_ended_task(self, failed_result: Dict[str, Any]) -> bool:
        if not _is_retryable_transport_error(failed_result):
            return False
        if not wait_for_unity(timeout=10.0):
            return False

        client = _get_default_client()
        status = client.call('workflow_session_status')
        if status.get('success'):
            current_task_id = status.get('currentTaskId')
            if not status.get('isRecording'):
                return True
            if self._task_id and current_task_id != self._task_id:
                return True
            if self._matches_status(status):
                retry_result = client.call('workflow_task_end')
                return bool(retry_result.get('success'))

        return False

    def __enter__(self):
        global _current_workflow_active
        start_result = _get_default_client().call('workflow_task_start', tag=self.tag, description=self.description)
        if not start_result.get('success'):
            if self._recover_started_task(start_result):
                return self
            with _workflow_lock:
                _current_workflow_active = False
            raise RuntimeError(start_result.get('error', 'workflow_task_start failed'))

        with _workflow_lock:
            _current_workflow_active = True
        self._started = True
        self._task_id = start_result.get('taskId')
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        global _current_workflow_active
        try:
            if self._started:
                end_result = _get_default_client().call('workflow_task_end')
                if not end_result.get('success'):
                    recovered = self._recover_ended_task(end_result)
                    if exc_type is None and not recovered:
                        raise RuntimeError(end_result.get('error', 'workflow_task_end failed'))
        finally:
            with _workflow_lock:
                _current_workflow_active = False
            self._started = False
            self._task_id = None
        return False  # Do not suppress exceptions

def workflow_context(tag: str, description: str = '') -> WorkflowContext:
    """Convenience function to create a WorkflowContext."""
    return WorkflowContext(tag, description)

def call_skill_with_retry(skill_name: str, max_retries: int = 3, retry_delay: float = 2.0, **kwargs) -> Dict[str, Any]:
    """Call a Unity skill with automatic retry logic for Domain Reload scenarios.

    Args:
        skill_name: Name of the Unity skill to call.
        max_retries: Maximum number of retry attempts after the initial call (default: 3, total attempts: 4).
        retry_delay: Delay in seconds between retry attempts.
        **kwargs: Additional arguments passed to call_skill.

    Returns:
        The result from call_skill, or the last result if all retries are exhausted.
    """
    last_result = None
    for attempt in range(1 + max_retries):
        result = call_skill(skill_name, **kwargs)

        is_connection_error = _is_retryable_transport_error(result)
        if not is_connection_error:
            return result

        last_result = result
        if attempt < max_retries:
            time.sleep(retry_delay)
    return last_result

def get_skills(category: str = None, operation: str = None, tags: str = None,
               read_only: bool = None, q: str = None) -> Dict[str, Any]:
    """Get list of available skills, optionally filtered by metadata.

    Args:
        category: Filter by SkillCategory (e.g. "GameObject", "Material").
        operation: Filter by SkillOperation (e.g. "Create", "Query").
        tags: Filter by tag (e.g. "batch", "hierarchy").
        read_only: Filter read-only skills (True/False).
        q: Text search across name, description, and tags.
    """
    try:
        client = _get_default_client()
        params = {}
        if category is not None: params["category"] = category
        if operation is not None: params["operation"] = operation
        if tags is not None: params["tags"] = tags
        if read_only is not None: params["readOnly"] = str(read_only).lower()
        if q is not None: params["q"] = q
        qs = f"?{urlencode(params)}" if params else ""
        response = client._session.get(f"{client.url}/skills{qs}", timeout=client.timeout)
        response.encoding = 'utf-8'
        return response.json()
    except Exception as e:
        return {"status": "error", "error": str(e)}

def get_skill_schema() -> Dict[str, Any]:
    """Get the canonical machine-readable skill schema.

    This is the preferred source for exact skill names, parameters, and metadata
    when prompt/token budget matters more than loading large SKILL.md files.
    """
    try:
        client = _get_default_client()
        response = client._session.get(f"{client.url}/skills/schema", timeout=client.timeout)
        response.encoding = 'utf-8'
        return response.json()
    except Exception as e:
        return {"status": "error", "error": str(e)}


def find_skills(intent: str, top_n: int = 10) -> Dict[str, Any]:
    """Server-side intent-based skill recommendation.

    Uses keyword scoring: name match (3pts), tag match (2pts), description match (1pt).
    Returns top-N ranked skills with relevance scores.

    Args:
        intent: Natural language description of what you want to do (e.g. "create red cube").
        top_n: Maximum number of results (default 10, max 50).
    """
    try:
        client = _get_default_client()
        params = {"intent": intent, "topN": str(top_n)}
        response = client._session.get(
            f"{client.url}/skills/recommend?{urlencode(params)}", timeout=client.timeout)
        response.encoding = 'utf-8'
        return response.json()
    except Exception as e:
        return {"status": "error", "error": str(e)}


def get_skill_chain(target_output: str, max_depth: int = 3) -> Dict[str, Any]:
    """Find skill producers and dependency chain for a specific output field via the server."""
    try:
        client = _get_default_client()
        params = {"output": target_output, "maxDepth": str(max_depth)}
        response = client._session.get(
            f"{client.url}/skills/chain?{urlencode(params)}", timeout=client.timeout)
        response.encoding = 'utf-8'
        return response.json()
    except Exception as e:
        return {"status": "error", "error": str(e)}


def health() -> bool:
    """Check if the current default Unity server is running."""
    try:
        client = _get_default_client()
        response = client._session.get(f"{client.url}/health", timeout=HEALTH_TIMEOUT)
        response.encoding = 'utf-8'
        return response.json().get("status") == "ok"
    except (requests.exceptions.RequestException, ValueError):
        return False


def is_unity_running() -> bool:
    """Alias for health()."""
    return health()


def wait_for_unity(timeout: float = 10.0, check_interval: float = 1.0) -> bool:
    """Wait for Unity REST server to become available again."""
    start_time = time.time()
    while time.time() - start_time < timeout:
        if health():
            return True
        time.sleep(check_interval)
    return False


def get_server_status() -> Dict[str, Any]:
    """Get detailed health information from the current Unity server."""
    try:
        client = _get_default_client()
        response = client._session.get(f"{client.url}/health", timeout=HEALTH_TIMEOUT)
        response.encoding = 'utf-8'
        return response.json()
    except requests.exceptions.ConnectionError:
        return {'status': 'offline', 'reason': 'Server not running or Unity recompiling'}
    except Exception as e:
        return {'status': 'error', 'reason': str(e)}


def create_script(name: str, template: str = 'MonoBehaviour', wait_for_compile: bool = True) -> Dict[str, Any]:
    """Create a script and optionally wait for recompilation to settle."""
    result = call_skill('script_create', name=name, template=template)
    compilation = result.get('compilation', {}) if isinstance(result, dict) else {}
    if result.get('success') and wait_for_compile and compilation.get('isCompiling'):
        time.sleep(2)
        if wait_for_unity(timeout=10):
            feedback = call_skill('script_get_compile_feedback', scriptPath=result['path'])
            if feedback.get('success'):
                result['compilation'] = {k: v for k, v in feedback.items() if k != 'success'}
    return result


_CLI_INT_PATTERN = re.compile(r'^[+-]?\d+$')
_CLI_FLOAT_PATTERN = re.compile(r'^[+-]?(?:\d+\.\d*|\.\d+|\d+[eE][+-]?\d+|\d+\.\d*[eE][+-]?\d+|\.\d+[eE][+-]?\d+)$')


def _parse_cli_value(value: str) -> Any:
    lower_value = value.lower()
    if lower_value == 'true':
        return True
    if lower_value == 'false':
        return False
    if _CLI_INT_PATTERN.fullmatch(value):
        try:
            return int(value)
        except ValueError:
            return value
    if _CLI_FLOAT_PATTERN.fullmatch(value):
        try:
            return float(value)
        except ValueError:
            return value
    return value

# ============================================================
# Main CLI Entry Point
# ============================================================
def main():
    """Command-line interface for Unity Skills."""
    import argparse

    parser = argparse.ArgumentParser(
        description='Unity Skills Python CLI',
        usage='python unity_skills.py [options] <skill_name> [param1=value1] ...'
    )
    parser.add_argument('--list', action='store_true', help='List all available skills')
    parser.add_argument('--list-instances', action='store_true', help='List active Unity instances')
    parser.add_argument('--port', type=int, default=None, help='Connect to specific port')
    parser.add_argument('--version', type=str, default=None, dest='unity_version',
                        help='Connect to Unity instance by version (e.g. "6", "2022", "2022.3")')
    parser.add_argument('skill_name', nargs='?', help='Skill name to execute')
    parser.add_argument('params', nargs='*', help='Skill parameters as key=value pairs')

    args = parser.parse_args()

    # Configure client based on CLI args
    if args.port or args.unity_version:
        global _default_client
        _default_client = UnitySkills(port=args.port, version=args.unity_version)

    if args.list:
        print(json.dumps(get_skills(), ensure_ascii=False, indent=2))
        return
    elif args.list_instances:
        print(json.dumps(list_instances(), ensure_ascii=False, indent=2))
        return

    if not args.skill_name:
        parser.print_help()
        sys.exit(1)

    # Parse parameters
    params = {}
    for arg in args.params:
        if '=' in arg:
            key, value = arg.split('=', 1)
            params[key] = _parse_cli_value(value)

    # Call the skill
    result = call_skill(args.skill_name, **params)

    # Pretty print the result
    print(json.dumps(result, ensure_ascii=False, indent=2))

if __name__ == '__main__':
    main()
